export const POST_MESSAGES = 'POST_MESSAGES';
export const POST_MESSAGES_SUCCESS = 'POST_MESSAGES_SUCCESS';
export const POST_MESSAGES_FAILED = 'POST_MESSAGES_FAILED';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';